# Generated by Django 5.0.3 on 2025-11-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_servers', models.IntegerField(default=0)),
                ('total_players', models.IntegerField(default=0)),
                ('open_lobbies', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Bot statuses',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MapStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('total_games', models.IntegerField(default=0)),
                ('total_valid_games', models.IntegerField(default=0)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('avg_game_duration', models.FloatField(default=0.0)),
                ('avg_players_per_game', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Map statistics',
                'ordering': ['-total_valid_games'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('guild_id', models.BigIntegerField()),
                ('player_count', models.IntegerField()),
                ('threshold', models.IntegerField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ServerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('server_name', models.CharField(max_length=255)),
                ('total_games', models.IntegerField(default=0)),
                ('total_valid_games', models.IntegerField(default=0)),
                ('last_game_date', models.DateTimeField(blank=True, null=True)),
                ('first_game_date', models.DateTimeField(blank=True, null=True)),
                ('avg_players_per_game', models.FloatField(default=0.0)),
                ('total_player_minutes', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Server statistics',
                'ordering': ['-total_valid_games'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(db_index=True, max_length=255)),
                ('server_name', models.CharField(max_length=255)),
                ('server_address', models.CharField(max_length=100)),
                ('map_name', models.CharField(db_index=True, max_length=100)),
                ('game_mode', models.CharField(default='Unknown', max_length=100)),
                ('region', models.CharField(default='Unknown', max_length=50)),
                ('lobby_start', models.DateTimeField(blank=True, null=True)),
                ('game_start', models.DateTimeField(db_index=True)),
                ('game_end', models.DateTimeField(blank=True, null=True)),
                ('players_at_start', models.IntegerField(default=0)),
                ('players_at_end', models.IntegerField(default=0)),
                ('max_players_during_game', models.IntegerField(default=0)),
                ('competitive', models.BooleanField(default=False)),
                ('autobalance', models.BooleanField(default=False)),
                ('rank_restricted', models.BooleanField(default=False)),
                ('is_valid_game', models.BooleanField(default=False)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-game_start'],
                'indexes': [models.Index(fields=['-game_start'], name='nebulous_bo_game_st_657298_idx'), models.Index(fields=['server_id', '-game_start'], name='nebulous_bo_server__aa9252_idx'), models.Index(fields=['map_name', '-game_start'], name='nebulous_bo_map_nam_b45ce0_idx'), models.Index(fields=['is_valid_game', '-game_start'], name='nebulous_bo_is_vali_e03828_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_players', models.IntegerField(default=0)),
                ('total_servers', models.IntegerField(default=0)),
                ('open_lobbies', models.IntegerField(default=0)),
                ('games_in_progress', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='nebulous_bo_timesta_9a81c8_idx')],
            },
        ),
    ]
