# Generated by Django 5.0.3 on 2025-11-18 03:31

from django.db import migrations, connection


def create_new_tables(apps, schema_editor):
    """Create the new statistics tables if they don't exist"""
    cursor = connection.cursor()
    
    # Check what tables exist
    cursor.execute("""
        SELECT name FROM sqlite_master 
        WHERE type='table' AND name LIKE 'nebulous_bot_%'
    """)
    existing_tables = {row[0] for row in cursor.fetchall()}
    
    # Only create tables that don't exist
    if 'nebulous_bot_gamesession' not in existing_tables:
        cursor.execute("""
            CREATE TABLE "nebulous_bot_gamesession" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "server_id" varchar(255) NOT NULL,
                "server_name" varchar(255) NOT NULL,
                "server_address" varchar(100) NOT NULL,
                "map_name" varchar(100) NOT NULL,
                "game_mode" varchar(100) NOT NULL,
                "region" varchar(50) NOT NULL,
                "lobby_start" datetime NULL,
                "game_start" datetime NOT NULL,
                "game_end" datetime NULL,
                "players_at_start" integer NOT NULL,
                "players_at_end" integer NOT NULL,
                "max_players_during_game" integer NOT NULL,
                "competitive" bool NOT NULL,
                "autobalance" bool NOT NULL,
                "rank_restricted" bool NOT NULL,
                "is_valid_game" bool NOT NULL,
                "duration_seconds" integer NULL,
                "created_at" datetime NOT NULL,
                "updated_at" datetime NOT NULL
            )
        """)
        cursor.execute('CREATE INDEX "nebulous_bo_game_st_657298_idx" ON "nebulous_bot_gamesession" ("game_start" DESC)')
        cursor.execute('CREATE INDEX "nebulous_bo_server__aa9252_idx" ON "nebulous_bot_gamesession" ("server_id", "game_start" DESC)')
        cursor.execute('CREATE INDEX "nebulous_bo_map_nam_b45ce0_idx" ON "nebulous_bot_gamesession" ("map_name", "game_start" DESC)')
        cursor.execute('CREATE INDEX "nebulous_bo_is_vali_e03828_idx" ON "nebulous_bot_gamesession" ("is_valid_game", "game_start" DESC)')
        cursor.execute('CREATE INDEX "nebulous_bot_gamesession_server_id_idx" ON "nebulous_bot_gamesession" ("server_id")')
        cursor.execute('CREATE INDEX "nebulous_bot_gamesession_map_name_idx" ON "nebulous_bot_gamesession" ("map_name")')
        cursor.execute('CREATE INDEX "nebulous_bot_gamesession_game_start_idx" ON "nebulous_bot_gamesession" ("game_start")')
    
    if 'nebulous_bot_playersnapshot' not in existing_tables:
        cursor.execute("""
            CREATE TABLE "nebulous_bot_playersnapshot" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "timestamp" datetime NOT NULL,
                "total_players" integer NOT NULL,
                "total_servers" integer NOT NULL,
                "open_lobbies" integer NOT NULL,
                "games_in_progress" integer NOT NULL
            )
        """)
        cursor.execute('CREATE INDEX "nebulous_bo_timesta_9a81c8_idx" ON "nebulous_bot_playersnapshot" ("timestamp" DESC)')
    
    if 'nebulous_bot_serverstatistics' not in existing_tables:
        cursor.execute("""
            CREATE TABLE "nebulous_bot_serverstatistics" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "server_id" varchar(255) NOT NULL UNIQUE,
                "server_name" varchar(255) NOT NULL,
                "total_games" integer NOT NULL,
                "total_valid_games" integer NOT NULL,
                "last_game_date" datetime NULL,
                "first_game_date" datetime NULL,
                "avg_players_per_game" real NOT NULL,
                "total_player_minutes" integer NOT NULL,
                "last_updated" datetime NOT NULL
            )
        """)
        cursor.execute('CREATE INDEX "nebulous_bot_serverstatistics_server_id_idx" ON "nebulous_bot_serverstatistics" ("server_id")')
    
    if 'nebulous_bot_mapstatistics' not in existing_tables:
        cursor.execute("""
            CREATE TABLE "nebulous_bot_mapstatistics" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "map_name" varchar(100) NOT NULL UNIQUE,
                "total_games" integer NOT NULL,
                "total_valid_games" integer NOT NULL,
                "last_played" datetime NULL,
                "avg_game_duration" real NOT NULL,
                "avg_players_per_game" real NOT NULL,
                "last_updated" datetime NOT NULL
            )
        """)
        cursor.execute('CREATE INDEX "nebulous_bot_mapstatistics_map_name_idx" ON "nebulous_bot_mapstatistics" ("map_name")')


class Migration(migrations.Migration):

    dependencies = [
        ('nebulous_bot', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_new_tables),
    ]
