# Generated by Django 5.0.3 on 2025-11-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebulous_bot', '0002_add_statistics_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='is_ongoing',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['is_ongoing', '-game_start'], name='nebulous_bo_is_ongo_d8133f_idx'),
        ),
    ]
