# Generated by Django 5.0.3 on 2025-11-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebulous_bot', '0003_add_is_ongoing_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='has_password',
            field=models.BooleanField(default=False),
        ),
    ]
