# Generated by Django 5.0.3 on 2025-11-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nebulous_bot', '0004_add_has_password_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapStatistics',
        ),
        migrations.DeleteModel(
            name='ServerStatistics',
        ),
    ]
