# Generated by Django 5.0.3 on 2025-11-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebulous_bot', '0005_remove_aggregated_statistics_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='LobbyWaitSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(db_index=True, max_length=255)),
                ('server_name', models.CharField(max_length=255)),
                ('lobby_start', models.DateTimeField(db_index=True)),
                ('lobby_end', models.DateTimeField(blank=True, null=True)),
                ('players_at_start', models.IntegerField(default=0)),
                ('players_at_end', models.IntegerField(default=0)),
                ('avg_players', models.FloatField(default=0.0)),
                ('max_players', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('player_hours', models.FloatField(default=0.0)),
                ('is_ongoing', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-lobby_start'],
                'indexes': [models.Index(fields=['-lobby_start'], name='nebulous_bo_lobby_s_3e354a_idx'), models.Index(fields=['server_id', '-lobby_start'], name='nebulous_bo_server__4b5a3a_idx'), models.Index(fields=['is_ongoing', '-lobby_start'], name='nebulous_bo_is_ongo_dd7343_idx')],
            },
        ),
    ]
