# Generated by Django 5.0.3 on 2026-05-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebulous_bot', '0007_commandlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildConfig',
            fields=[
                ('guild_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status_channel_id', models.BigIntegerField(blank=True, null=True)),
                ('notification_channel_id', models.BigIntegerField(blank=True, null=True)),
                ('notification_role_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guild config',
                'verbose_name_plural': 'Guild configs',
            },
        ),
        migrations.DeleteModel(
            name='LobbyWaitSession',
        ),
        migrations.RenameIndex(
            model_name='commandlog',
            new_name='nebulous_bo_timesta_d59e10_idx',
            old_name='nebulous_b_timesamp_4248dd_idx',
        ),
        migrations.RenameIndex(
            model_name='commandlog',
            new_name='nebulous_bo_guild_i_072896_idx',
            old_name='nebulous_b_guild_i_01a4c1_idx',
        ),
        migrations.RenameIndex(
            model_name='commandlog',
            new_name='nebulous_bo_user_id_8c1c38_idx',
            old_name='nebulous_b_user_id_6ffb19_idx',
        ),
        migrations.AlterField(
            model_name='commandlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
