# Generated by Django 4.2.30 on 2026-07-06 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nebulous_bot", "0008_guildconfig_and_drift_cleanup"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NotificationLog",
        ),
    ]
