# Generated by Django 4.2.30 on 2026-07-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nebulous_bot", "0009_remove_notificationlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdviceProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("add", "Add advice"), ("remove", "Remove advice")],
                        max_length=10,
                    ),
                ),
                ("advice_text", models.TextField(blank=True)),
                ("target_entry_id", models.CharField(blank=True, max_length=32)),
                ("author_id", models.BigIntegerField()),
                ("author_name", models.CharField(max_length=255)),
                ("guild_id", models.BigIntegerField()),
                ("channel_id", models.BigIntegerField()),
                ("message_id", models.BigIntegerField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending vote"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("removed", "Removed by later vote"),
                            ("expired", "Ballot lost"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("up_votes", models.IntegerField(default=0)),
                ("down_votes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
